
ID DEBUG_ITEM
	NAME "Debug\0"
	TYPE TOOL 
	WIDTH 1 
	HEIGHT 1 
	STACKSIZE 1 
	TEX "assets/items/ITEM_TEST.png"
	ENI

ID TEST_ITEM	
	NAME "Dank MayMay\0" 
	TYPE TOOL 
	WIDTH HLINE 
	HEIGHT HLINE 
	STACKSIZE 420 
	TEX "assets/items/ITEM_TEST.png"
	ENI

ID PLAYER_BAG	
	NAME "Your Bag\0" 
	TYPE EQUIP 
	WIDTH HLINE*5 
	HEIGHT HLINE*5 
	STACKSIZE 1 
	TEX "assets/items/ITEM_TEST.png"
	ENI

ID FLASHLIGHT 	
	NAME "Flashlight\0" 
	TYPE TOOL 
	WIDTH HLINE*2 
	HEIGHT HLINE*4 
	STACKSIZE 1 
	TEX "assets/items/ITEM_TEST.png" 
	ENI

ID SWORD_WOOD 	
	NAME "Wood Sword\0" 
	TYPE SWORD 
	WIDTH HLINE*4 
	HEIGHT HLINE*10 
	STACKSIZE 1 
	TEX "assets/items/ITEM_SWORD.png" 
	STOP
